### ISSUE TITLE
Support for Teams and OneDrive

### ISSUE THREAD

**Issue by hinrichd** [pbowden-msft/NukeOffKeychain#8]
Just asking if Teams and OneDrive will also supported in a future release?

**Comment by pbowden-msft** [comment]
@hinrichd if you haven't done so already, you might want to check out the 'License Reset' package, which is part of Office-Reset, as it is a little more tailored for handling resets for Teams and OneDrive. See https://office-reset.com/macadmins/

**Comment by hinrichd** [comment]
Thank you for pointing out to Office-Reset! For my workflow this tool is a bit too extensive, because it will download office apps if it is not at-least version which is too time-consuming as also is not proxy aware. The Version should be controlled from the MDM server. Just want to nuke of the keychain not a full repair.
I will take a look into the postinstall scripts from the office-rest.pkg to catch the keychain items!

**Comment by pbowden-msft** [comment]
@hinrichd Office-Reset consists of several PKG modules that are tasked with individual actions. Specifically, the postinstall script for https://office-reset.com/download/Microsoft_License_Reset_1.6.pkg is the direct equivalent of NukeOffKeychain.
