### ISSUE TITLE
Question: How can I completely remove/reset any Right Management Service (RMS) / Azur Information Protection (AIP) settings?

### ISSUE THREAD

**Issue by hkirschk** [pbowden-msft/NukeOffKeychain#9]
Hi Paul, I tried your NukeOffKeychain script and the proposal at https://apple.stackexchange.com/questions/395879/how-do-i-log-out-or-reset-microsofts-rms-aip-azure-information-protection (which is a shortened version of your script) to completely remove/reset any Right Management Service (RMS) / Azur Information Protection (AIP) settings. It does not work for me. The problem is that something on RMS/AIP was installed when I worked for a customer of my employer a long time ago. Now my employer is also using RMS/AIP to protect documents, but I get that old customer RMS/AIP login when I try to open a document protected by my employer, I cannot switch to my employee's RMS/AIP login. Do you have any ideas how to solve that? We're using O365 on Mac.

**Comment by pbowden-msft** [comment]
Hi @hkirschk I'd advise you to use my new Office-Reset tool at https://office-reset.com and perform a factory reset.
This should take care of the problem. Hope this helps!

**Comment by hkirschk** [comment]
Hej Paul, yes it worked! Thanks a lot for your tool! -- Heiko
